yarnPath: ".yarn/releases/yarn-berry.cjs"
enableGlobalCache: true
packageExtensions:
  "skypack@*":
    dependencies:
      tar: "*"
  "@npmcli/metavuln-calculator@*":
    dependencies:
      json-parse-even-better-errors: "*"
  "bin-links@*":
    dependencies:
      mkdirp-infer-owner: "*"
